### ISSUE TITLE
Add an opt-out and opt-in feature for pinging you when your line quivers

### ISSUE THREAD

**Issue by Peter-developer01** [SE-Utility-Bot/utility-bot#65]
So I've been reviewing my inbox and I see there:
 - posts from Charcoal HQ (I did opt-in manually);
 - a comments, replies, or posts from people who noticed my own;
 - and your Utility Bot's "your fish is ready!".

It *was* fun in the first times. However when you start to see so much "your fish is ready!" items, this is starting to be annoying.

---

I'm requesting a new command that would allow me to opt-in or opt-out the fish pings.

For example,
 - the command for opt-out would be something like "optout fishpings";
 - the command for opt-in would be something like "optin fishpings".

You can store the config for each user in the, for example, JSON file. You can of course select any file format you like.  
And remember, to avoid the confusion, you store the keys as user IDs, not user names.

**Comment by PlaceReporter99** [comment]
Storing the user IDs would be impossible. I’ll store the usernames instead. A text file containing those who opted out should be enough. I’ll have to use `os.system` to commit the changes while the program is running.

**Comment by Peter-developer01** [comment]
Why you can't store the user IDs? Storing usernames would be a bad idea because two users can have same usernames, chat allows it.

**Comment by PlaceReporter99** [comment]
I am testing an implementation

**Comment by PlaceReporter99** [comment]
I’m adding a database to this, the command will be `setting fishping false` to opt out. You will be opted out by default.
